{% set name = "google-cloud-os-login" %}
{% set version = "2.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 874233d9a4e285c9a631c68cca4fa066fba3105d91edf69de7021730b00e0ac0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - google-api-core-grpc >=1.31.5,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - proto-plus >=1.15.0

test:
  imports:
    - grpc
    - google.cloud.oslogin
    - google.cloud.oslogin_v1
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-oslogin
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Cloud OS Login API client library
  description: "Google Cloud OS Login API is a Google Cloud service that lets you manage SSH access to your instances using IAM without having to create and manage individual SSH keys. OS Login maintains a consistent Linux user identity across VM instances and is the recommended way to manage many users across multiple instances\
    \ or projects.\nSee the [quick start guide](https://googleapis.dev/python/oslogin/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/oslogin/latest/index.html
  dev_url: https://github.com/googleapis/python-oslogin

extra:
  recipe-maintainers:
    - parthea
    - xylar
